# One-time database setup for the Bridge Register.
#   powershell -ExecutionPolicy Bypass -File setup-db.ps1
# Creates the database, loads schema + sample bridges, creates the API login
# (random password written to server\.env) and your first admin user.
$ErrorActionPreference = 'Stop'
$psql = 'C:\Program Files\PostgreSQL\16\bin\psql.exe'
$env:PGHOST = 'localhost'
$env:PGPORT = '5432'
$db = 'bridge_registry'

function Read-Secret([string]$prompt) {
    $s = Read-Host $prompt -AsSecureString
    [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($s))
}
# Pipe SQL through stdin so passwords never appear on a command line.
function Invoke-Sql([string]$database, [string]$sql) {
    $out = $sql | & $psql -U postgres -d $database -v ON_ERROR_STOP=1 -q -tA
    if ($LASTEXITCODE) { throw "SQL failed on $database" }
    $out
}
function Invoke-SqlFile([string]$file) {
    Write-Host "  running $(Split-Path $file -Leaf)"
    & $psql -U postgres -d $db -v ON_ERROR_STOP=1 -q -f $file
    if ($LASTEXITCODE) { throw "Failed: $file" }
}
function New-RandomPassword {
    $bytes = New-Object byte[] 24
    [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
    [Convert]::ToBase64String($bytes) -replace '[+/=]', 'x'
}

try {
    Write-Host "`n== 1. Connect to PostgreSQL ==" -ForegroundColor Cyan
    $env:PGPASSWORD = Read-Secret 'Password for the postgres account (typing is hidden)'
    Invoke-Sql 'postgres' 'SELECT 1' | Out-Null
    Write-Host '  connected OK' -ForegroundColor Green

    Write-Host "`n== 2. Database and tables ==" -ForegroundColor Cyan
    if (Invoke-Sql 'postgres' "SELECT 1 FROM pg_database WHERE datname = '$db'") {
        Write-Host "  database $db already exists - keeping existing tables and data" -ForegroundColor Yellow
    } else {
        Invoke-Sql 'postgres' "CREATE DATABASE $db" | Out-Null
        Invoke-SqlFile "$PSScriptRoot\db\01_schema.sql"
        Invoke-SqlFile "$PSScriptRoot\db\02_seed.sql"
        Write-Host '  tables created, sample bridges loaded' -ForegroundColor Green
    }

    Write-Host "`n== 3. API login (bridge_api) ==" -ForegroundColor Cyan
    $apiPw = New-RandomPassword
    Invoke-Sql $db @"
DO `$`$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'bridge_api') THEN
    ALTER ROLE bridge_api LOGIN PASSWORD '$apiPw';
  ELSE
    CREATE ROLE bridge_api LOGIN PASSWORD '$apiPw';
  END IF;
END `$`$;
"@ | Out-Null
    Invoke-SqlFile "$PSScriptRoot\db\03_grants.sql"
    $envText = @"
# Generated by setup-db.ps1 - keep this file private
PGHOST=localhost
PGPORT=5432
PGDATABASE=$db
PGUSER=bridge_api
PGPASSWORD=$apiPw
PORT=3000
TOKEN_DAYS=60
"@
    [IO.File]::WriteAllText("$PSScriptRoot\server\.env", $envText)   # UTF-8 without BOM
    Write-Host '  bridge_api ready, password saved to server\.env' -ForegroundColor Green

    Write-Host "`n== 4. Your admin account for the app ==" -ForegroundColor Cyan
    $user = Read-Host 'Username (press Enter for "admin")'
    if (-not $user) { $user = 'admin' }
    $name = Read-Host 'Full name'
    if (-not $name) { $name = 'System Administrator' }
    do {
        $p1 = Read-Secret 'App password (min 8 characters)'
        $p2 = Read-Secret 'Repeat app password'
        if ($p1 -ne $p2) { Write-Host '  passwords do not match' -ForegroundColor Yellow }
        elseif ($p1.Length -lt 8) { Write-Host '  too short' -ForegroundColor Yellow }
    } until ($p1 -eq $p2 -and $p1.Length -ge 8)
    $q = { param($s) $s -replace "'", "''" }
    Invoke-Sql $db @"
SELECT CASE WHEN EXISTS (SELECT 1 FROM app_user WHERE username = lower('$(& $q $user)'))
  THEN (SELECT set_password('$(& $q $user)', '$(& $q $p1)'))::text
  ELSE create_user('$(& $q $user)', '$(& $q $name)', '$(& $q $p1)', 'admin', NULL)::text END;
"@ | Out-Null
    Write-Host "  admin user '$($user.ToLower())' ready" -ForegroundColor Green

    Write-Host "`n== Done ==" -ForegroundColor Cyan
    & $psql -U postgres -d $db -c 'SELECT * FROM v_bridge_summary'
}
catch {
    Write-Host "`nSETUP FAILED: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}
finally {
    Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
}
